spring:
  datasource:
    url: jdbc:mysql://db:3306/review_service_db
    username: reboot
    password: reboot1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080