spring:
  datasource:
    url: jdbc:mysql://localhost:3307/review_service_db
    username: reboot
    password: reboot1234
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: create-drop